"""empty message

Revision ID: 050c59d7a70d
Revises: 958068719e35
Create Date: 2023-03-18 10:05:12.027950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '050c59d7a70d'
down_revision = '958068719e35'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_dubbings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('slide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_dubbings_id'), 'audio_dubbings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_dubbings_id'), table_name='audio_dubbings')
    op.drop_table('audio_dubbings')
    # ### end Alembic commands ###
