"""empty message

Revision ID: 4034bb023e76
Revises: 3de2a048482e
Create Date: 2023-03-17 21:44:58.723323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4034bb023e76'
down_revision = '3de2a048482e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
