"""empty message

Revision ID: 83b57d70b0a2
Revises: 4034bb023e76
Create Date: 2023-03-17 21:45:29.979262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83b57d70b0a2'
down_revision = '4034bb023e76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slides', sa.Column('formatted_content', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slides', 'formatted_content')
    # ### end Alembic commands ###
