"""empty message

Revision ID: 958068719e35
Revises: 83b57d70b0a2
Create Date: 2023-03-17 22:08:44.612140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '958068719e35'
down_revision = '83b57d70b0a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_dubbings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('audio', sa.String(), nullable=True),
    sa.Column('slide_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slide_id'], ['slides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audio_dubbings_id'), 'audio_dubbings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audio_dubbings_id'), table_name='audio_dubbings')
    op.drop_table('audio_dubbings')
    # ### end Alembic commands ###
